### ISSUE TITLE
namespace info is not reloaded in new pd server after leader change

### ISSUE THREAD

**Issue by lerencao** [pingcap/pd#1178] opened 2018-08-07 04:54 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?  If possible, provide a recipe for reproducing the error.
  A pd server is down, and leader transfer to another pd (namespaces were created during the old server is leading), new pd server didn't reload the ns infos, and caused huge data rebalancing.

2. What did you expect to see?

3. What did you see instead?

4. What version of PD are you using (`pd-server -V`)?
  v2.0.2

**Comment by disksing** [comment] 2018-08-07 05:14
Hi @lerencao , this is a bug caused by both design and implementation, thanks for your feedback. In order to restore the cluster, the temporary solution is to restart the PD in turn. Please note that namespace is an experimental feature which is unstable and does not guarantee future compatibility. Please avoid using it in a production environment.

**Comment by lerencao** [comment] 2018-08-13 09:27
One quick solution is reload server.classifier.namespacesInfo from kv  in `campaignLeader` function, like the `scheduleOpt` did.

**Comment by lerencao** [comment] 2018-08-13 09:28
If it's an accepted solution, will give a pr on it.

**Comment by disksing** [comment] 2018-08-13 10:00
@lerencao Thanks for your willing for help. It can be fixed by reloading namespace classifier in `campaignLeader`, but I think it will be better to move `server.namespaceClassifier` into `RaftCluster`, which is automatically recreated everytime when the pd instance becomes leader.
If you have any question, please don't hesitate to let me know.

**Closed** 2018-08-15 02:51 UTC
Labels: area/namespace, kind/bug, kind/question
