### ISSUE TITLE
[Discuss] What if one store belongs to more than one namespaces?

### ISSUE THREAD

**Issue by lerencao** [pingcap/pd#964] opened 2018-02-26 08:32 UTC
The current implementation of `tableNamespaceClassifier.GetStoreNamespace` only return one ns.
If two namespaces contain the same store, only one returned, and which one returned is undefined(If the go map has no predefined order when itering).

If the word `namespace` has the same meaning as that in k8s, and the `store` has the same meaning as `host` in k8s, then two namespaces should able to use the same store. And in real deployment, this case can be very common.
So should we support this feature?

**Comment by disksing** [comment] 2018-02-26 10:38
hi @lerencao , the concepts we are using is different from k8s, for instance, a _store_ refers to a _tikv-server_ instance rather than a _host_ in our context. And a _store_ can only belong to a single namespace for now, this restriction is by design.

I wonder if you have any special scenario that need a _store_ to belong to multiple namespaces? If so, please feel free to communicate with us, we can discuss whether to support it later.

**Comment by lerencao** [comment] 2018-02-26 11:11
@disksing  thx for the explanation. What I mean is that it's a choice between one-to-one mappings and many-to-one mappings, just like the lightweight thread and physical thread.
There is no special scenario currently, only some plan of using namespace classifier to separate databases of different businesses. Resources are limited, less important dbs (of different businesses, aka different namespaces) need be shared on the same stores.
 As far as I can see, If many-to-one mapping doesn't complicate things(will try to modify the code to see the difference),  it's more suitable, as one-to-one is just a special case of it.

**Comment by disksing** [comment] 2018-02-26 11:28
The purpose of the introducing of namespace is to isolate resources. If a store belongs to two namespaces, this isolation is in fact violated -- heavy requests from one namespace can affect the other namespace.
For your case, I think you can create a single namespace and register all unimportant dbs to it. Hope my answer can help.

**Comment by lerencao** [comment] 2018-02-27 09:48
Using many-to-one mappings still enable the one-to-one mapping. It's just a special case.

**Comment by disksing** [comment] 2018-02-27 10:40
It is currently already many-to-one now :-) You see, many stores/tables can be configured to the same namespace. I think you are suggesting a many-to-many support -- which we have not found any case really need.

**Comment by lerencao** [comment] 2018-02-27 12:09
Yes, you are right. What I meant many was _many namespaces onto one store_. Considering other stores, `many-to-many` is the word.

Still, I think it's a more general solution. If fact, yesterday, I changed the `tableNamespaceClassifier.GetStoreNamespace` to `GetStoreNamespaces`, and will use it in my environments.

If some other guy comes up similar questions, please reconsider  it.

**Comment by rleungx** [comment] 2020-05-11 10:34
The namespace feature has been removed in the latest several versions. Close it. Feel free to reopen it.

**Closed by rleungx** 2020-05-11 10:34 UTC
Labels: type/question
